### ISSUE TITLE
(Un)marshalling error should not crash whole process

### ISSUE THREAD

**Issue by ericbottard** [projectriff/node-function-invoker#108]
Seems like this is what is happening (not sure what the incorrect input is/was, as this ran "behind my back") Maybe carriage return sent from liiklus-client?

```
cnb@repeater-processor-f2qxx-795967487d-7c99k:/workspace$ NODE_DEBUG=riff node /layers/io.projectriff.node/riff-invoker-node/server.js
RIFF 102: Ready to process signals
RIFF 102: New invocation started
RIFF 102: Streaming pipeline initialized
RIFF 102: Input signal received
RIFF 102: Start signal received: application/json
RIFF 102: Wiring 2 input stream(s)
RIFF 102: Wiring 1 output stream(s)
RIFF 102: Ready to process data
RIFF 102: Input signal received
RIFF 102: Forwarding data for input #0
RIFF 102: Input signal received
RIFF 102: error from unmarshaller
RIFF 102: Error occurred - ending pipeline now
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error
    at InputUnmarshaller._transform (/layers/io.projectriff.node/riff-invoker-node/lib/input-unmarshaller.js:43:22)
    at InputUnmarshaller.Transform._read (_stream_transform.js:190:10)
    at InputUnmarshaller.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at InputUnmarshaller.Writable.write (_stream_writable.js:299:11)
    at StreamingPipeline._write (/layers/io.projectriff.node/riff-invoker-node/lib/streaming-pipeline.js:146:31)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at StreamingPipeline.Writable.write (_stream_writable.js:299:11)
Emitted 'error' event at:
    at Stream._send (/layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:998:18)
    at Stream.write (/layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:1658:18)
    at /layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:686:15
    at /layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:3588:17
    at /layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:1604:9
    at Stream.s._send (/layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:1560:9)
    at Stream.write (/layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:1658:18)
    at Stream._send (/layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:984:26)
    at push (/layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:1526:19)
    at /layers/org.cloudfoundry.npm/node_modules/node_modules/highland/lib/index.js:2212:13
```

**Comment by fbiville** [comment]
After digging, it appears the crash happens with https://github.com/projectriff-samples/node-repeater.
When an error occurs (e.g.: send a payload with a bogus content-type), the default behavior of a Highland.js stream is to throw.
One needs to add an [explicit error handler](http://highlandjs.org/#errors) and discard the error.

**Comment by fbiville** [comment]
https://github.com/projectriff-samples/node-repeater/pull/1 should solve this particular issue with Highland.js.
