### ISSUE TITLE
Requesting functions hangs fovever if the (request-reply) function fails (UnhandledPromiseRejectionWarning)

### ISSUE THREAD

**Issue by fbiville** [projectriff/node-function-invoker#133]
If users define a function such as:

```js
module.exports = (x) => {
        if (x === 0) {
                throw new Error('Division by zero');
        }
        return 100 / x;
}
```

deploy it and request it as follows:
```sh
curl http://XXX -H'Content-Type:application/json' -d'0' -H'Accept:text/plain' -v
```

The request will hang forever:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST / HTTP/1.1
> Host: XXX
> User-Agent: curl/7.64.1
> Content-Type:application/json
> Accept:text/plain
> Content-Length: 1
>
* upload completely sent off: 1 out of 1 bytes
```

The invoker logs are as follows:

```
RIFF 13426: Ready to process signals
RIFF 13426: New invocation started
RIFF 13426: Promoting request-reply function to streaming function
RIFF 13426: Streaming pipeline initialized
RIFF 13426: Input signal received
RIFF 13426: Start signal with: output content types: text/plain, input names: [in], output names: [out]
RIFF 13426: Wiring 1 input stream(s)
RIFF 13426: Wiring 1 output stream(s)
RIFF 13426: Ready to process data
RIFF 13426: Input signal received
RIFF 13426: Forwarding data for input #0
(node:13426) UnhandledPromiseRejectionWarning: Error
    at MappingTransform._handleError (/Users/fbiville/workspace/node-function-invoker/lib/mapping-transform.js:33:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
RIFF 13426: Ending input streams
```

**Comment by fbiville** [comment]
Fixed by https://github.com/projectriff/node-function-invoker/commit/0945c63aebe2a14650933ff71b72068c87755c3d

**Comment by fbiville** [comment]
Contrary to what I thought, this still happens, e.g. with this function:
```js
module.exports = (x) => {
        if (x === 0) {
                throw new Error('Division by zero');
        }
        return 100 / x;
}
```
and this request:
```
curl http://localhost:8080 -H'Content-Type:application/json' -d'0' -H'Accept:text/plain' -v
```
