### ISSUE TITLE
Node 12 not working

### ISSUE THREAD

**Issue by kapolos** [projectriff/node-function-invoker#182]
This is on a newly installed 0.6 snapshot (`187e783565eb69c76af017d1d9e461432350a51a`) and I also had the same issue on 0.5.

App (knative runtime) works fine with node 10 but after setting this

```
  "engines": {
    "node": "12"
  },
```

the runtime dies like this:

```
Waiting for deployer "pquery" to become ready...
Starting streaming-http-adapter 0.5.1-snapshot b607f3d37585fe77b7c3a7a2ea5c96dac3f44c07
foobar/pquery-deployer-nxkbd-tcmwp-deployment-69d754c97d-v5gh2[user-container]:
/layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/src/grpc_extension.js:55
    throw error;
    ^
foobar/pquery-deployer-nxkbd-tcmwp-deployment-69d754c97d-v5gh2[user-container]:
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v72-linux-x64-glibc
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
Require stack:
- /layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/src/grpc_extension.js
- /layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/src/client_interceptors.js
- /layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/src/client.js
- /layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/index.js
- /layers/io.projectriff.node/riff-invoker-node/lib/streaming-pipeline.js
- /layers/io.projectriff.node/riff-invoker-node/lib/invoker.js
- /layers/io.projectriff.node/riff-invoker-node/server.js
    at Object.<anonymous> (/layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/layers/io.projectriff.node/riff-invoker-node/node_modules/grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  code: 'MODULE_NOT_FOUND'
}
Child process exited with exit status 1
```

This is the part where the builder picks the image to use:

```
[builder] Node Engine Buildpack 0.0.168
[builder]   Resolving Node Engine version
[builder]     Candidate version sources (in priority order):
[builder]       package.json -> "12"
[builder]       <unknown>    -> "*"
[builder]
[builder]     Selected Node Engine version (using package.json): 12.16.1
[builder]
[builder]   Executing build process
[builder]     Installing Node Engine 12.16.1
[builder]       Completed in 3.804s
[builder]
[builder]   Configuring environment
[builder]     NODE_ENV     -> "production"
[builder]     NODE_HOME    -> "/layers/org.cloudfoundry.node-engine/node"
[builder]     NODE_VERBOSE -> "false"
[builder]
[builder]     Writing profile.d/0_memory_available.sh
[builder]       Calculates available memory based on container limits at launch time.
[builder]       Made available in the MEMORY_AVAILABLE environment variable.
[builder]
[builder] Yarn Install Buildpack 0.1.10
[builder]   Reusing cached layer /layers/org.cloudfoundry.yarn-install/yarn
[builder]
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       yarn.lock -> Found
[builder]
[builder]     Selected default build process: 'yarn install'
[builder]
[builder]   Reusing cached layer /layers/org.cloudfoundry.yarn-install/modules
[builder]
```

**Comment by scothis** [comment]
Hmm, we run the invoker unit tests against node 12. But we're not testing with the buildpack against node 12. I quickly tried to building our test function with node 12 and it worked. Are you able to share the function source that is failing?

**Comment by kapolos** [comment]
Thank you @scothis ! Based on your response, I investigated some more and I think I've figured out the root cause. It looks like during the build process Docker's cache is using an existing (v. 10 based docker layer), therefore the image ends up with the wrong files.

![image](https://user-images.githubusercontent.com/10794126/79138672-93316400-7dbd-11ea-96e0-e3a24d9520d9.png)

To verify this, I did the following test:

a) Set the node engine to 12 and created a `buildwith12first` function/deployment, using the same project as the one that errors out. It worked!

b) Set the node engine to 10 and created a `buildwith10first` function/deployment, again using the same project. It worked. But then I changed the node engine to 12, kept the function/deployment name the same and boom - it errors out.

So I guess the workaround would be to just delete the image from the registry. I'm not sure there's an easy fix for this so perhaps just documenting the gotcha somewhere is the best option.

**Comment by scothis** [comment]
Thanks for the extra digging. We should be invalidating the layer cache for the invoker when the node-engine layer changes. I'm going to transfer this issue to the node-function-buildpack repo since that's where the issue will need to be fixed.

There is also a PR (#181) to switch from the c++ based grpc library to a pure js version which should also side step this issue.
