### ISSUE TITLE
Function fails to be invoked when the artifact is `package.json`

### ISSUE THREAD

**Issue by fbiville** [projectriff/node-function-invoker#74]
Following [this doc](https://projectriff.io/docs/getting-started/gke/), the current documented command to create a square function is:
```console
riff function create square \
  --git-repo https://github.com/projectriff-samples/node-square \
  --artifact package.json \
  --image gcr.io/$GCP_PROJECT/square \
  --wait --verbose
```
However, when run with the documented invoked:
```console
riff service invoke square --text -- -w '\n' -d 8
```
It results in a failure:
```console
curl 35.204.90.231/ -H 'Host: square.default.example.com' -H 'Content-Type: text/plain' -w '\n' -d 8
TypeError: fn is not a function
    at DestroyableTransform._transform (/workspace/io.projectriff.riff/riff-invoker-node/lib/interaction-models/request-reply.js:36:34)
    at DestroyableTransform.Transform._read (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Duplexify.ondata (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at Duplexify.emit (events.js:182:13)
    at Duplexify.Readable.read (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_readable.js:469:26)
    at flow (/workspace/io.projectriff.riff/riff-invoker-node/node_modules/readable-stream/lib/_stream_readable.js:813:34)
```

When creating the function without any `--artifact`, it runs well:
```console
riff function create square \
  --git-repo https://github.com/projectriff-samples/node-square \
  --image gcr.io/$GCP_PROJECT/square-fbiville \
  --wait --verbose
[...]
riff function create completed successfully
```
```console
riff service invoke square --text -- -w '\n' -d 8
curl 35.204.90.231/ -H 'Host: square.default.example.com' -H 'Content-Type: text/plain' -w '\n' -d 8
64
```

**Comment by scothis** [comment]
`package.json` isn't a valid module to require in Node. `require('./package.json')` will return the value of package.json as a JSON parsed object rather than the main module the file references. The correct behavior is to require the directory that contains the package.json.

Supporting package.json as the artifact is a relic of the previous invoker build system for Node. The correct mitigation is to drop the artifact definition.
